# Brownie configuration file
# https://eth-brownie.readthedocs.io/en/stable/config.html
# automatically fetch contract sources from Etherscan
autofetch_sources: true
# required external contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.1
pytest:
    # these settings replace the defaults when running pytest
    gas_limit: 6721975
    default_contract_owner: true
    reverting_tx_gas_limit: 6721975
    revert_traceback: true
compiler:
    solc:
        version: 0.8.7
        optimize: true
        remappings:
          - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.3.1/contracts"
# automatically fetch contract sources from Etherscan
autofetch_sources: True
